# Generated by Django 3.2.4 on 2021-06-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_controller', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
