# Generated by Django 3.2.4 on 2021-06-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_controller', '0003_dog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dog',
            new_name='Cat',
        ),
    ]
